name: Build Flet APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Build Android APK
        run: flet build apk --yes --module-name misa

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: misa-apk
          path: build/apk/*.apk
